### ISSUE TITLE
关于本项目部署的几点疑问

### ISSUE THREAD

**Issue by Cyame** [zyzsdy/aqua-button#30]
zyzsdy你好，我目前在进行粥按钮的搭建。现进度较理想，故想先行测试一下部署的事宜，但遇到了一些困难（部署失败）。

因此关于项目部署我想请教一下以下几点：

1、一开始想利用Github-Pages部署环境，直接把静态页丢到master/docs内进行部署，再通过CNAME重定向指定到我们的域名。但因为之前我基本都是利用vue-cli的脚手架进行搭建，会存在一个config文件夹对build进行配置。但本项目中似乎是用npm进行初始化（故没有此配置）因此想请教一下是否还可以利用gh-pages进行部署。（或者另开branch也可以接受但是具体路径配置应该如何进行呢）

> 参考：
> https://www.jianshu.com/p/93c939fc939a

2、关于项目内的tsconfig的用途不明。在src中也没有发现类似typescript的代码，因此也想顺便请教这里的配置项是否与部署有关？

3、如果试图部署在VPS服务器上，是否直接开docker或者使用nginx代理将文件夹映射即可，是否需要其他配置呢？

多谢！

**Comment by Cyame** [comment]
Follow up:

主要是想询问一下是否可以重新初始化本项目之后补全依赖再进行gh-Pages的部署，因为除了Vue方面的东西都不太熟悉，因此尝试前想先请教一下是否有更方便快捷的部署方式）

**Comment by blacktunes** [comment]
项目用的vue-cli3，和旧版本一样，命令行执行`npm run build`命令就可以在dist目录打包静态页面，旧版本的vue-cli的build和config文件夹的配置已经简化，需要修改可以在目录新建一个`vue.config.js`文件，配置参考可以查看[官方文档](https://cli.vuejs.org/zh/config/)，

**Comment by zyzsdy** [comment]
这个项目当然也是用vue-cli脚手架搭的，虽然router.js的mode是history但是**只有一个页面**，应该不会影响gh pages的部署。实际上也有人将此项目部署在Github Pages上也没有出什么问题。

tsconfig.json应该是为了给VSCode智能提示用的。这个项目用的脚手架版本比较老了，新版脚手架里不会有这种东西。

理论上讲部署本项目只需要将编译出的dist目录直接作为http主目录就行了。至于你的部署失败，很大可能是其他的问题而非本代码库里这些细枝末节的小问题。

**Comment by Cyame** [comment]
了解 感谢解答！目前在尝试中~


> 另外目前初步有打算去做上传功能（通过提交Form直接编辑渲染进程里的config）但问题在于如何把文件搬运到仓库（保持同步 否则一旦退掉环境再去收集文件可能会比较繁琐...），但是GitHub-Pages是不是也不能支持直接传文件到仓库... 所以不知道具体该如何实现

**Comment by Cyame** [comment]
> 2. 请在`vue.config.js`里添加`publicPath: process.env.NODE_ENV === 'production' ? './' : '/'`，修改资源路径，`public/index.html`里的图标地址同理，请把`href`修改为`./favicon.ico`，`vue.config.js`的[配置参考](https://www.baidu.com/link?url=79Ipz9OMmgTKq_7Npfgawx7MijAKawpRMofowhwaPniVc_OLrND_OyYso50Wy02n&wd=&eqid=dfb127890010c72a000000065f15ffd7)

感谢解答，关于在Github的部署存在一点补充（指正）：

因为我这边的路径没有其他指定，因此默认是在`https://cyame.github.io/okayu-button/`下的。Deploy之后发现空白，查看控制台发现GET请求失败。发现请求路径是`https://cyame.github.io/css...`，发现原因。

因此这里需要把`publicPath: process.env.NODE_ENV === 'production' ? './' : '/'`变更为`publicPath: process.env.NODE_ENV === 'production' ? '/okayu-button/' : '/'`即可正确部署。

至于master/docs文件夹还是gh-pages上存在，似乎都没有影响，相对路径都是直接映射的。

**Comment by blacktunes** [comment]
> > 1. 请在`vue.config.js`里添加`publicPath: process.env.NODE_ENV === 'production' ? './' : '/'`，修改资源路径，`public/index.html`里的图标地址同理，请把`href`修改为`./favicon.ico`，`vue.config.js`的[配置参考](https://www.baidu.com/link?url=79Ipz9OMmgTKq_7Npfgawx7MijAKawpRMofowhwaPniVc_OLrND_OyYso50Wy02n&wd=&eqid=dfb127890010c72a000000065f15ffd7)
> 
> 感谢解答，关于在Github的部署存在一点补充（指正）：
> 
> 因为我这边的路径没有其他指定，因此默认是在`https://cyame.github.io/okayu-button/`下的。Deploy之后发现空白，查看控制台发现GET请求失败。发现请求路径是`https://cyame.github.io/css...`，发现原因。
> 
> 因此这里需要把`publicPath: process.env.NODE_ENV === 'production' ? './' : '/'`变更为`publicPath: process.env.NODE_ENV === 'production' ? '/okayu-button/' : '/'`即可正确部署。
> 
> 至于master/docs文件夹还是gh-pages上存在，似乎都没有影响，相对路径都是直接映射的。

看了zyzsdy的回答我也发现了，当时发现页面空白我就直接改成了`hash模式`和`./`，发现正常就直接回答了，`hash模式`不需要服务器环境所以`./`就是正确的资源路径，但是`history模式`下默认资源路径为'/'，指向Github Pages的根目录，所以需要加上仓库地址

**Comment by zyzsdy** [comment]
> > 1. 请在`vue.config.js`里添加`publicPath: process.env.NODE_ENV === 'production' ? './' : '/'`，修改资源路径，`public/index.html`里的图标地址同理，请把`href`修改为`./favicon.ico`，`vue.config.js`的[配置参考](https://www.baidu.com/link?url=79Ipz9OMmgTKq_7Npfgawx7MijAKawpRMofowhwaPniVc_OLrND_OyYso50Wy02n&wd=&eqid=dfb127890010c72a000000065f15ffd7)
> 
> 感谢解答，关于在Github的部署存在一点补充（指正）：
> 
> 因为我这边的路径没有其他指定，因此默认是在`https://cyame.github.io/okayu-button/`下的。Deploy之后发现空白，查看控制台发现GET请求失败。发现请求路径是`https://cyame.github.io/css...`，发现原因。
> 
> 因此这里需要把`publicPath: process.env.NODE_ENV === 'production' ? './' : '/'`变更为`publicPath: process.env.NODE_ENV === 'production' ? '/okayu-button/' : '/'`即可正确部署。
> 
> 至于master/docs文件夹还是gh-pages上存在，似乎都没有影响，相对路径都是直接映射的。

哦，确实。本项目不支持部署在子目录下。。。。。。。

cname搞个根目录部署就好了，url也更好看些（x
