### ISSUE TITLE
加一个勾选项可以让阿夸音重叠播放

### ISSUE THREAD

**Issue by redwine001** [zyzsdy/aqua-button#7]

**Comment by zyzsdy** [comment]
也就是说你想要点新按钮的时候不关闭原有语音吗？

**Comment by redwine001** [comment]
对，你说的没错。
但希望能加到一个可选功能上，因为除了傻笑combo，其他声音重叠播放应该会变成阿夸菜市场。

**Comment by zyzsdy** [comment]
Thanks to @blacktunes for the feature in # 16 that allows voice overlap. This issue has been completed.
